name: maven deploy
run-name: Deploy to registry
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven
      - name: Set pom version with tag name
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}
      - name: Create settings.xml
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: |
          username=${{ env.MAVEN_CENTRAL_USERNAME }}
          password=${{ env.MAVEN_CENTRAL_PASSWORD }}
          cat <<EOF > settings.xml
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>$username</username>
                <password>$password</password>
              </server>
            </servers>
          </settings>
          EOF
      - name: Deploy to Maven Central Package Registry
        shell: bash
        run: mvn --settings settings.xml deploy
